### ISSUE TITLE
RacketGhost crashes at startup

### ISSUE THREAD

**Issue by mrksbrg** [Troddel/RacketGhost#27]
After patching to 1.5.0 a crash has been reported on Samsung Galaxy Express 2:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.markusborg.test/com.markusborg.ui.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2447)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2507)
    at android.app.ActivityThread.access$900(ActivityThread.java:172)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:146)
    at android.app.ActivityThread.main(ActivityThread.java:5692)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
    at com.markusborg.logic.Setting.<init>(Setting.java:53)
    at com.markusborg.logic.LogHandler.<init>(LogHandler.java:44)
    at com.markusborg.ui.MainActivity.onCreate(MainActivity.java:66)
    at android.app.Activity.performCreate(Activity.java:5541)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
    ... 11 more

**Comment by mrksbrg** [comment]
This bug only appears if early versions of RacketGhost has been previously installed on the device.
